#!/bin/bash
while [ $# -gt 0 ]; do
	in_file="$1"
	dpi=300
    gs -o "${in_file}_crushed.pdf" -sDEVICE=pdfwrite -dDownsampleColorImages=true -dDownsampleGrayImages=true -dDownsampleMonoImages=true -dColorImageResolution=${dpi} -dGrayImageResolution=${dpi} -dMonoImageResolution=${dpi} -dColorImageDownsampleThreshold=1.0 -dGrayImageDownsampleThreshold=1.0 -dMonoImageDownsampleThreshold=1.0 -dNoOutputFonts "${in_file}"

	shift
done
