#!/bin/bash
while [ $# -gt 0 ]; do
	input_file=$1
	file=`echo "$input_file" | sed 's/\.\w*$/.mp4/'`
	/usr/bin/ffmpeg -i "$file" -vf "fps=12,scale=360:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop 0 "$file".gif
	shift
done
