#!/bin/bash
while [ $# -gt 0 ]; do
	picture=$1
	png_file=`echo "$picture" | sed 's/\.\w*$/.png/'`
	toolbox run /usr/bin/pngquant "$png_file" --quality 80 --speed 1 --strip --ext -pngquant.png
	shift
done
