#!/bin/bash
while [ $# -gt 0 ]; do
	input_file=$1
	file=`echo "$input_file" | sed 's/\.\w*$/.mp4/'`
	toolbox run /usr/bin/ffmpeg -i "$file" -vcodec libx265 -crf 28 -vf scale=-1:720 "$file"-720.mp4
	shift
done
